import fs from "node:fs";
import path from "node:path";

type PredictionFile={date:string;fixtures:any[];scan?:{leagueEntriesChecked?:number;status?:string}};
function latestPredictions():PredictionFile{
 const dir=path.join(process.cwd(),"data","predictions");
 const files=fs.readdirSync(dir).filter(x=>/^\\d{4}-\\d{2}-\\d{2}\\.json$/.test(x)).sort().reverse();
 if(!files[0]) return {date:"No published slate",fixtures:[]};
 return JSON.parse(fs.readFileSync(path.join(dir,files[0]),"utf8")) as PredictionFile;
}
export default function Home(){const predictions=latestPredictions();const matches=predictions.fixtures;return <main><nav><b>FI<span>H</span></b><div>Matches　 Predictions　 Leagues　 Teams　 Stats　 Intelligence</div></nav><section className="hero"><p className="eyebrow">DAILY FOOTBALL RESEARCH</p><h1>Every match. Researched.<br/><em>Calculated. Predicted.</em></h1><p>One recommended betting market per fixture, selected from the model probabilities. Correct score remains a forecast, not the recommended bet.</p><div className="stats"><b>{matches.length}<small>Predictions</small></b><b>{matches.filter((x:any)=>x.model?.recommendedBet).length}<small>Recommended bets</small></b><b>{predictions.scan?.leagueEntriesChecked??0}<small>Leagues checked</small></b></div></section><section className="panel"><header><div><p className="eyebrow">LATEST PUBLISHED INTELLIGENCE · {predictions.date}</p><h2>Model selections</h2></div><span>{predictions.scan?.status==="complete"?"League scan complete":"Latest verified publication"}</span></header><div className="filters">Recommended Bet　 Correct Score　 1X2　 BTTS　 Goals</div><div className="table"><div className="row head"><span>Fixture</span><span>Recommended Bet</span><span>Bet %</span><span>Correct Score</span><span>Score %</span><span>1</span><span>X</span><span>2</span><span>Confidence</span></div>{matches.map((m:any)=>{const x=m.model;const b=x.recommendedBet;return <div className="row" key={m.fixtureKey}><span><small>{m.league} · {m.kickoff}</small><strong>{m.homeTeam} <i>vs</i> {m.awayTeam}</strong></span><span className="correct">{b?<><mark>{b.pick}</mark><small>{b.market} · {b.rating}</small></>:<mark>NO BET</mark>}</span><span>{b?\`${b.probability}%\`:"—"}</span><span className="correct"><mark>{x.correctScore.score}</mark></span><span>{x.correctScore.probability}%</span><span>{x.homeWin}%</span><span>{x.draw}%</span><span>{x.awayWin}%</span><span><mark>{x.confidence}</mark><small>λ {x.lambdaHome} – {x.lambdaAway}</small></span></div>})}</div></section><footer>FOOTBALL INTELLIGENCE HUB · Model probabilities are estimates, not guarantees. NO BET means no supported market cleared the selection threshold.</footer></main>}
