import fs from "node:fs";import path from "node:path";import {execFileSync} from "node:child_process";import {validateDailyResearch} from "./research-canonical";
const TZ="Africa/Johannesburg",TODAY=new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),i=process.argv.indexOf("--date"),DATE=(i>=0?process.argv[i+1]:"")||process.env.FIH_DATE||TODAY,root=process.cwd();
if(!/^\d{4}-\d{2}-\d{2}$/.test(DATE))throw new Error("INVALID_FIH_DATE");if(DATE<TODAY)throw new Error("DATE_MODE_MISMATCH historical date requires backtest pipeline");
const tsx=(...a:string[])=>execFileSync(process.execPath,["node_modules/tsx/dist/cli.mjs",...a],{stdio:"inherit",env:{...process.env,FIH_DATE:DATE}}),read=(p:string)=>JSON.parse(fs.readFileSync(path.join(root,p),"utf8"));
tsx("scripts/daily-run-ledger.ts","reconcile","--date",DATE);let ledger=read("data/run-state/"+DATE+".json"),eligible=ledger.fixtures.filter((f:any)=>f.eligible),ids=eligible.map((f:any)=>String(f.id));
let researchOk=false;try{if(!ledger.researchRunId)throw new Error("STEP2_RESEARCH_RUN_NOT_STARTED");const v=validateDailyResearch(root,DATE,ids,"PREDICTION",ledger.researchRunId);if(ledger.researchRunId!==v.researchRunId)throw new Error("STEP2_RESEARCH_GENERATION_MISMATCH");researchOk=true}catch(e){console.error("STEP2_CHATGPT_RESEARCH_REQUIRED "+String(e));}
if(!researchOk&&!ledger.researchRunId){tsx("scripts/daily-run-ledger.ts","start-research","--date",DATE);ledger=read("data/run-state/"+DATE+".json");if(!ledger.researchRunId)throw new Error("STEP2_RESEARCH_RUN_START_FAILED");tsx("scripts/research-checkpoint.ts","init","--date",DATE,"--research-run-id",ledger.researchRunId);const work=read("data/research-work/"+DATE+"/manifest.json");if(work.researchRunId!==ledger.researchRunId||work.expectedCount!==ids.length)throw new Error("STEP2_RESEARCH_WORK_INIT_MISMATCH");}
if(!researchOk){const fixtures=eligible.map((f:any)=>({fixtureId:String(f.id),home:f.home,away:f.away,competition:f.competition,kickoff:f.kickoff}));fs.mkdirSync(path.join(root,"data/research-queue"),{recursive:true});fs.writeFileSync(path.join(root,"data/research-queue",DATE+".json"),JSON.stringify({schema:"fih-chatgpt-research-queue-v2",date:DATE,researchRunId:ledger.researchRunId||null,generatedAt:new Date().toISOString(),count:fixtures.length,executor:"CHATGPT_WEB_SEARCH",workingCheckpoint:"data/research-work/"+DATE,canonicalCommitPolicy:"ONE_BATCH_AFTER_FULL_VALIDATION_AND_PROMOTION",fixtures},null,2)+"\n");}
if(!researchOk){tsx("scripts/contract-gate.ts","--verdict","RECOVERING","--date",DATE,"--rules","REC-001,REC-005,RESUME-001,RESP-001","--evidence","canonical-step2-missing");throw new Error("FIH_RUN_UNFINISHED_STEP2");}
tsx("scripts/daily-model-runner.ts");tsx("scripts/daily-decision-runner.ts");tsx("scripts/daily-run-ledger.ts","reconcile","--date",DATE);ledger=read("data/run-state/"+DATE+".json");
const unfinished=ledger.fixtures.filter((f:any)=>f.eligible&&f.state!=="COMPLETE");if(unfinished.length)throw new Error("FIH_RUN_UNFINISHED "+unfinished.length);
const decisions=read("data/decisions/"+DATE+".json"),by=new Map(decisions.fixtures.map((d:any)=>[String(d.fixtureId),d])),predictions:any[]=[];for(const f of eligible){const d:any=by.get(String(f.id));if(!d)throw new Error("DECISION_COVERAGE_MISSING "+f.id);if(d.publishable)predictions.push({fixtureId:String(f.id),home:f.home,away:f.away,competition:f.competition,kickoff:f.kickoff,decision:d.decision,market:d.market||null,modelVersion:d.modelVersion||null,reason:d.reason||null});}
const pp=path.join(root,"data/predictions",DATE+".json");fs.mkdirSync(path.dirname(pp),{recursive:true});fs.writeFileSync(pp,JSON.stringify({schema:"fih-daily-predictions-v1",date:DATE,status:"COMPLETE",generatedAt:new Date().toISOString(),eligibleFixtures:eligible.length,publishableCount:predictions.length,predictions},null,2)+"\n");console.log("DAILY_FINALIZATION_READY "+DATE);
