import fs from "node:fs";
import path from "node:path";

type State="PENDING"|"RESEARCH_VERIFIED"|"MODEL_VERIFIED"|"DECISION_VERIFIED"|"COMPLETE"|"EXCLUDED";
type Item={id:string;home:string;away:string;competition:string;kickoff:string|null;eligible:boolean;exclusionReason:string|null;state:State;updatedAt:string|null};
type Ledger={schema:string;date:string;timezone:string;board:{fetchedAt:string;fixtureCount:number;stageCount:number};createdAt:string;updatedAt:string;fixtures:Item[];counts:Record<string,number>;next:{fixtureId:string;state:State}|null};

const ROOT=process.cwd(), TZ="Africa/Johannesburg";
const arg=(name:string)=>{const i=process.argv.indexOf(name);return i>=0?process.argv[i+1]:undefined};
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const now=()=>new Date().toISOString();
const ledgerPath=(d:string)=>path.join(ROOT,"data","run-state",d+".json");
const readJson=(p:string)=>JSON.parse(fs.readFileSync(p,"utf8"));
function eventId(e:any,s:any){return String(e?.Eid??e?.Id??[s?.CompId,e?.T1?.[0]?.Nm,e?.T2?.[0]?.Nm,e?.Esd].filter(Boolean).join(":"))}
function name(x:any){return String(x?.[0]?.Nm??x?.[0]?.name??"UNKNOWN")}
function kickoff(e:any){const raw=e?.Esd??e?.Epsd??e?.startTime??null;return raw==null?null:String(raw)}
function exclusion(e:any,s:any){const status=String(e?.Eps??"").toUpperCase();if(status!=="NS")return "NOT_PREMATCH";const text=[s?.CompN,s?.Snm,s?.Cnm,e?.T1?.[0]?.Nm,e?.T2?.[0]?.Nm].filter(Boolean).join(" ").toLowerCase();if(/women|\bw\b/.test(text))return "WOMEN";if(/\bu[- ]?\d{2}\b|under[- ]?\d{2}|youth/.test(text))return "YOUTH";if(/reserve|reserves|\bu23\b|\bu21\b|\bu20\b|\bu19\b|\bu18\b|\bu17\b|\bii\b|\b2\b/.test(text))return "RESERVE_OR_DEVELOPMENT";if(/university|academia|academy|akatemia|juniors?/.test(text))return "NON_SENIOR";return null}
function counts(items:Item[]){const out:any={boardTotal:items.length,eligible:0,excluded:0,PENDING:0,RESEARCH_VERIFIED:0,MODEL_VERIFIED:0,DECISION_VERIFIED:0,COMPLETE:0,EXCLUDED:0};for(const x of items){if(x.eligible)out.eligible++;else out.excluded++;out[x.state]=(out[x.state]||0)+1}return out}
function next(items:Item[]){const x=items.find(f=>f.eligible&&f.state!=="COMPLETE");return x?{fixtureId:x.id,state:x.state}:null}
function board(d:string){const p=path.join(ROOT,"data","today_fixture.json");if(!fs.existsSync(p))throw new Error("MISSING data/today_fixture.json");const x=readJson(p);if(x.schema!=="fih-today-fixture-v1"||x.date!==d||x.timezone!==TZ)throw new Error("fixture board date/schema/timezone invalid");const stages=Array.isArray(x.payload?.Stages)?x.payload.Stages:[];const events=stages.flatMap((s:any)=>(Array.isArray(s.Events)?s.Events:[]).map((e:any)=>({e,s})));if(!events.length||events.length!==x.fixtureCount)throw new Error("fixture board count mismatch");return {x,events}}
function init(d:string){const {x,events}=board(d),p=ledgerPath(d);fs.mkdirSync(path.dirname(p),{recursive:true});let old:Ledger|null=null;if(fs.existsSync(p)){try{old=readJson(p)}catch{}}
 const oldMap=new Map((old?.fixtures||[]).map(f=>[f.id,f]));const fixtures:Item[]=events.map(({e,s}:any)=>{const id=eventId(e,s),o=oldMap.get(id);const reason=exclusion(e,s),eligible=!reason,oldState=o?.state;const state:State=eligible?(oldState&&oldState!=="EXCLUDED"?oldState:"PENDING"):"EXCLUDED";return {id,home:name(e.T1),away:name(e.T2),competition:String(s?.CompN??s?.Snm??"UNKNOWN"),kickoff:kickoff(e),eligible,exclusionReason:reason,state,updatedAt:o?.updatedAt??null}});
 const ts=now();const out:Ledger={schema:"fih-daily-run-ledger-v1",date:d,timezone:TZ,board:{fetchedAt:x.fetchedAt,fixtureCount:x.fixtureCount,stageCount:x.stageCount},createdAt:old?.createdAt??ts,updatedAt:ts,fixtures,counts:counts(fixtures),next:next(fixtures)};fs.writeFileSync(p,JSON.stringify(out,null,2)+"\n");return out}
function verify(d:string){const {x,events}=board(d),p=ledgerPath(d);if(!fs.existsSync(p))throw new Error("MISSING run ledger");const l:Ledger=readJson(p);if(l.schema!=="fih-daily-run-ledger-v1"||l.date!==d||l.timezone!==TZ)throw new Error("ledger identity invalid");const ids=new Set(events.map(({e,s}:any)=>eventId(e,s)));if(l.fixtures.length!==ids.size||l.board.fixtureCount!==x.fixtureCount)throw new Error("ledger/board fixture count mismatch");for(const f of l.fixtures){if(!ids.has(f.id))throw new Error("orphan ledger fixture "+f.id);if(f.eligible&&f.state==="EXCLUDED")throw new Error("eligible fixture incorrectly excluded "+f.id);if(!f.eligible&&f.state!=="EXCLUDED")throw new Error("excluded fixture has active state "+f.id)}const c=counts(l.fixtures);for(const k of Object.keys(c))if(c[k]!==l.counts[k])throw new Error("ledger count mismatch "+k);return l}
function advance(d:string){const id=arg("--fixture"),to=arg("--to") as State;if(!id||!to)throw new Error("advance requires --fixture ID --to STATE");const order:State[]=["PENDING","RESEARCH_VERIFIED","MODEL_VERIFIED","DECISION_VERIFIED","COMPLETE"];if(!order.includes(to))throw new Error("invalid state");const l=verify(d),f=l.fixtures.find(x=>x.id===id);if(!f)throw new Error("fixture not in authoritative board");if(!f.eligible||f.state==="EXCLUDED")throw new Error("excluded fixture cannot advance");if(order.indexOf(to)<order.indexOf(f.state))throw new Error("state regression refused");f.state=to;f.updatedAt=now();l.updatedAt=now();l.counts=counts(l.fixtures);l.next=next(l.fixtures);fs.writeFileSync(ledgerPath(d),JSON.stringify(l,null,2)+"\n");return l}
const cmd=process.argv[2]||"verify",d=arg("--date")||today();let result:any;
if(cmd==="init"||cmd==="reconcile")result=init(d);else if(cmd==="verify")result=verify(d);else if(cmd==="advance")result=advance(d);else throw new Error("usage: daily-run-ledger.ts init|reconcile|verify|advance [--date YYYY-MM-DD] [--fixture ID --to STATE]");
console.log(JSON.stringify({ok:true,date:d,counts:result.counts,next:result.next,path:"data/run-state/"+d+".json"},null,2));