import fs from "node:fs";import path from "node:path";
const DATE=process.env.FIH_DATE||new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Johannesburg",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),root=process.cwd(),mp=path.join(root,"data/model",DATE+".json"),out=path.join(root,"data/decisions",DATE+".json");
if(!fs.existsSync(mp))throw new Error("CANONICAL_DAILY_MODEL_MISSING");const m=JSON.parse(fs.readFileSync(mp,"utf8"));if(m.schema!=="fih-daily-model-v2"||m.date!==DATE||!Array.isArray(m.fixtures))throw new Error("CANONICAL_DAILY_MODEL_INVALID");
const fixtures=m.fixtures.map((x:any)=>{if(x.status==="INSUFFICIENT_DATA")return {fixtureId:String(x.fixtureId),decision:"NO_MODEL",publishable:false,reason:"INSUFFICIENT_VERIFIED_MODEL_INPUT",modelVersion:x.modelVersion||x.version};
 if(x.status!=="CALCULATED")throw new Error("MODEL_STATUS_UNSUPPORTED "+x.fixtureId);
 // Locked rules deliberately define qualitative strong-support gates for HOME/AWAY and approximate goal territories,
 // but calibration is NOT_CALIBRATED and no numeric HOME/AWAY threshold is authorized. Do not invent one.
 // OVER 2.5 may qualify only around 4.5+ expected total; BTTS YES only around 2+ expected goals for each side.
 const over=Number(x.expectedGoals?.total)>=4.5, btts=Number(x.expectedGoals?.home)>=2&&Number(x.expectedGoals?.away)>=2;
 if(over&&btts){const op=Number(x.probabilities?.overUnder25?.over)||0,bp=Number(x.probabilities?.btts?.yes)||0;return op>=bp?{fixtureId:String(x.fixtureId),decision:"BET",publishable:true,market:"OVER 2.5",reason:"LOCKED_EXPECTED_GOAL_TERRITORY",modelVersion:x.modelVersion||x.version}:{fixtureId:String(x.fixtureId),decision:"BET",publishable:true,market:"BTTS YES",reason:"LOCKED_EXPECTED_GOAL_TERRITORY",modelVersion:x.modelVersion||x.version};}
 if(over)return {fixtureId:String(x.fixtureId),decision:"BET",publishable:true,market:"OVER 2.5",reason:"LOCKED_EXPECTED_GOAL_TERRITORY",modelVersion:x.modelVersion||x.version};
 if(btts)return {fixtureId:String(x.fixtureId),decision:"BET",publishable:true,market:"BTTS YES",reason:"LOCKED_EXPECTED_GOAL_TERRITORY",modelVersion:x.modelVersion||x.version};
 return {fixtureId:String(x.fixtureId),decision:"NO_BET",publishable:false,reason:"NO_AUTHORIZED_STRONG_MARKET; HOME/AWAY numeric qualification remains uncalibrated",modelVersion:x.modelVersion||x.version};});
const a={schema:"fih-daily-decisions-v2",date:DATE,generatedAt:new Date().toISOString(),fixtureCount:fixtures.length,fixtures};fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(a,null,2)+"\n");const v=JSON.parse(fs.readFileSync(out,"utf8"));if(v.date!==DATE||v.fixtureCount!==m.fixtureCount||v.fixtures.length!==m.fixtures.length)throw new Error("DAILY_DECISION_PERSIST_VERIFY_FAILED");console.log(JSON.stringify({ok:true,date:DATE,fixtures:fixtures.length,canonical:out},null,2));
