import fs from "node:fs"; import path from "node:path";
import {loadRows,buildInput,type Row,type CompetitionType} from "./web-historical-backtest";
const norm=(s:any)=>String(s??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").trim();
const toks=(s:any)=>new Set(norm(s).split(/\s+/).filter(x=>x&&!["fc","cf","sc","afc","fk","club","de","the","ac","cd","ca"].includes(x)));
const sim=(a:any,b:any)=>{const x=toks(a),y=toks(b);if(!x.size||!y.size)return 0;let n=0;for(const t of x)if(y.has(t))n++;return n/Math.max(x.size,y.size)};
const nonSenior=(f:any)=>/\b(u[- ]?\d{2}|u\d{2}|under[- ]?\d{2}|youth|academy|reserve|women|femin|femen|ladies)\b/i.test([f.league,f.stage,f.homeTeam,f.awayTeam].join(" "));
const ctype=(f:any):CompetitionType=>/friend/i.test(f.league)?"friendly":(/UEFA|CAF|CONCACAF|CONMEBOL|AFC|OFC|international/i.test(String(f.country))?"international":"club");
function infer(rows:Row[],f:any){const prior=rows.filter(r=>r.date<f.date),ds=[...new Set(prior.map(r=>r.division))];let best:any=null;for(const division of ds){const rr=prior.filter(r=>r.division===division);let h=0,a=0;for(const r of rr){h=Math.max(h,sim(f.homeTeam,r.home),sim(f.homeTeam,r.away));a=Math.max(a,sim(f.awayTeam,r.home),sim(f.awayTeam,r.away))}const v=(h+a)/2;if(h>=.6&&a>=.6&&(!best||v>best.value))best={division,value:v}}return best}
async function main(){const date=process.argv[2];if(!date||!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error("Usage: npm run daily:enrich -- YYYY-MM-DD");const file=path.join(process.cwd(),"data/daily-evidence",date+".json");const ev=JSON.parse(fs.readFileSync(file,"utf8")),rows=await loadRows();let modelled=0,noModel=0,excluded=0;
for(const f of ev.fixtures){if(f.eligibility==="excluded"){excluded++;f.researchComplete=true;f.modelLevel="no-model";f.noModelReason=f.exclusionReason??"Excluded before research";continue}if(nonSenior(f)){excluded++;f.eligibility="excluded";f.researchComplete=true;f.modelLevel="no-model";f.exclusionReason="Excluded non-senior or separate-category competition";f.noModelReason=f.exclusionReason;continue}
const m=infer(rows,f);if(!m){noModel++;f.researchComplete=true;f.modelLevel="no-model";f.noModelReason="No reliable historical competition/team mapping after Basic evidence search";continue}const same=rows.filter(r=>r.division===m.division&&r.date<date),meta=same.at(-1);if(!meta){noModel++;f.researchComplete=true;f.modelLevel="no-model";f.noModelReason="No completed pre-kickoff competition history";continue}
const target:Row={division:m.division,leagueId:meta.leagueId,date,home:f.homeTeam,away:f.awayTeam,hg:0,ag:0,source:"data/today_fixture.json",seasonMode:meta.seasonMode,competitionType:ctype(f),international:ctype(f)!=="club"};const pool=[...rows.filter(r=>r.date<date),target],input=buildInput(pool,pool.length-1);f.sources=[...new Set([...(f.sources??[]),...same.map(r=>r.source)])];f.researchComplete=true;if(!input){noModel++;f.modelLevel="no-model";f.noModelReason="Basic fallback exhausted: fewer than 3 reliable prior matches or unusable competition baseline";continue}f.modelInput=input;f.modelLevel="basic";f.sampleSize=input.sampleSize;f.researchMethod="deterministic-basic";f.researchMatchConfidence=+m.value.toFixed(3);modelled++}
ev.enrichedAt=new Date().toISOString();ev.enrichment={method:"FIH deterministic Basic fallback using completed pre-kickoff public results",historicalRows:rows.length,modelInputFixtures:modelled,noModelFixtures:noModel,excludedFixtures:excluded};fs.writeFileSync(file,JSON.stringify(ev,null,2)+"\n");console.log(JSON.stringify({file:path.relative(process.cwd(),file),fixtures:ev.fixtures.length,modelled,noModel,excluded},null,2))}
main().catch(e=>{console.error(e);process.exit(1)});