import fs from "node:fs";import path from "node:path";import {validateDailyResearch,validateResearchArtifact} from "./research-canonical";
const DATE=process.env.FIH_DATE||new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Johannesburg",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),root=process.cwd();
const q=path.join(root,"data/research-queue",DATE+".json"),i=path.join(root,"data/research-inbox",DATE+".json"),out=path.join(root,"data/research",DATE+".json");
if(!fs.existsSync(q)||!fs.existsSync(i))throw new Error("RESEARCH_QUEUE_OR_INBOX_MISSING");
const queue=JSON.parse(fs.readFileSync(q,"utf8")),inbox=JSON.parse(fs.readFileSync(i,"utf8"));if(queue.schema!=="fih-research-queue-v1"||queue.date!==DATE||inbox.schema!=="fih-research-inbox-v1"||inbox.date!==DATE)throw new Error("RESEARCH_INPUT_IDENTITY_INVALID");
const by=new Map(inbox.results.map((r:any)=>[String(r.fixtureId),r])),fixtures:any[]=[];
for(const f of queue.fixtures){const r:any=by.get(String(f.fixtureId));if(!r)throw new Error("RESEARCH_RESULT_MISSING "+f.fixtureId);if(!r.facts?.form||!r.facts?.standings||!r.facts?.headToHead||!r.facts?.squadAvailability||!r.facts?.schedule||!r.facts?.competitionContext||!Array.isArray(r.sourceMetadata))throw new Error("RESEARCH_RESULT_INCOMPLETE "+f.fixtureId);for(const s of r.sourceMetadata)if(!s?.url||!s?.retrievedAt||!Array.isArray(s.supports))throw new Error("RESEARCH_SOURCE_METADATA_INVALID "+f.fixtureId);
 fixtures.push({fixtureId:String(f.fixtureId),fixture:{home:f.home,away:f.away,competition:f.competition,kickoff:f.kickoff},researchedAt:r.researchedAt||new Date().toISOString(),sourceMetadata:r.sourceMetadata,facts:r.facts,evidenceStatus:r.evidenceStatus||"PARTIAL",requiredModelMatchSeries:r.requiredModelMatchSeries||"UNAVAILABLE",verifiedInputs:r.verifiedInputs||{},integrity:r.integrity||"Evidence retained only when source-supported; missing fields UNAVAILABLE."});}
const artifact={schema:"fih-daily-research-v3",date:DATE,mode:"PREDICTION",generatedAt:new Date().toISOString(),fixtureCount:fixtures.length,fixtures},ids=queue.fixtures.map((f:any)=>String(f.fixtureId));validateResearchArtifact(artifact,DATE,ids,"PREDICTION");fs.mkdirSync(path.dirname(out),{recursive:true});const tmp=out+".tmp";fs.writeFileSync(tmp,JSON.stringify(artifact,null,2)+"\n");fs.renameSync(tmp,out);validateDailyResearch(root,DATE,ids,"PREDICTION");console.log(JSON.stringify({ok:true,date:DATE,canonical:out,fixtures:fixtures.length},null,2));
