import fs from "node:fs";import path from "node:path";
type League={id:string;country:string;name:string;tier:number};
const arg=(n:string)=>{const i=process.argv.indexOf(n);return i<0?undefined:process.argv[i+1]},from=arg("--from"),to=arg("--to");
if(!from||!to)throw new Error("Usage: npm run backtest:research -- --from YYYY-MM-DD --to YYYY-MM-DD");
const root=process.cwd(),leagues=(JSON.parse(fs.readFileSync(path.join(root,"data/leagues.json"),"utf8")).leagues as League[]);
const dates:string[]=[];for(let d=new Date(from+"T00:00:00Z"),e=new Date(to+"T00:00:00Z");d<=e;d.setUTCDate(d.getUTCDate()+1))dates.push(d.toISOString().slice(0,10));
const leagueDays=dates.flatMap(date=>leagues.map((l,index)=>({date,leagueIndex:index+1,leagueId:l.id,country:l.country,leagueName:l.name,status:"pending-web-research",fixturesDiscovered:0,fixturesProcessed:0,sources:[],note:"ChatGPT must web-search this exact league/date. Dataset/API absence cannot complete this checkpoint."})));
const file=path.join(root,`data/backtest-evidence/${from}_to_${to}.research.json`);
fs.mkdirSync(path.dirname(file),{recursive:true});
fs.writeFileSync(file,JSON.stringify({status:"in-progress",range:{from,to},researchMode:"chatgpt-web-primary",rules:["automation/AGENT_INSTRUCTIONS.md","automation/RESEARCH_RULES.md","automation/MODEL_RULES.md","automation/HISTORICAL_BACKTEST.md"],configuredLeagues:leagues.length,expectedLeagueDays:leagueDays.length,leagueDays,fixtures:[]},null,2)+"\n");
console.log(JSON.stringify({file:path.relative(root,file),status:"in-progress",configuredLeagues:leagues.length,expectedLeagueDays:leagueDays.length,instruction:"Populate/checkpoint this manifest through verified ChatGPT web research before evidence collection."},null,2));
