import fs from "node:fs";import path from "node:path";
type L={id:string;country:string;name:string};
type Raw={date:string;kickoff?:string;leagueId:string;homeTeam:string;awayTeam:string;homeGoals:number;awayGoals:number;source:string};
const arg=(n:string)=>{const i=process.argv.indexOf(n);return i<0?undefined:process.argv[i+1]},from=arg("--from"),to=arg("--to");
if(!from||!to)throw new Error("Usage: npm run backtest:research -- --from YYYY-MM-DD --to YYYY-MM-DD");
const root=process.cwd(), leagues=(JSON.parse(fs.readFileSync(path.join(root,"data/leagues.json"),"utf8")).leagues as L[]);
const adapter=process.env.BACKTEST_RESULTS_URL;
if(!adapter)throw new Error("BACKTEST_RESULTS_URL is required. It must return JSON {fixtures:[{date,kickoff,leagueId,homeTeam,awayTeam,homeGoals,awayGoals,source}], coverage:[{date,leagueId,verified,sources}]} for the requested from/to range plus warm-up history.");
const u=new URL(adapter);u.searchParams.set("from",from);u.searchParams.set("to",to);u.searchParams.set("warmup","10");
const res=await fetch(u,{headers:{accept:"application/json"}});if(!res.ok)throw new Error("Historical source HTTP "+res.status);
const data=await res.json() as {fixtures:Raw[];coverage:any[]};if(!Array.isArray(data.fixtures)||!Array.isArray(data.coverage))throw new Error("Invalid historical source payload");
const prior=(team:string,cut:string)=>data.fixtures.filter(x=>(x.homeTeam===team||x.awayTeam===team)&&((x.kickoff??x.date)<cut)).sort((a,b)=>(b.kickoff??b.date).localeCompare(a.kickoff??a.date)).slice(0,10);
const avg=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const gfga=(rows:Raw[],team:string)=>({gf:rows.map(x=>x.homeTeam===team?x.homeGoals:x.awayGoals),ga:rows.map(x=>x.homeTeam===team?x.awayGoals:x.homeGoals)});
const leagueBefore=(id:string,cut:string)=>data.fixtures.filter(x=>x.leagueId===id&&(x.kickoff??x.date)<cut);
const fixtures=data.fixtures.filter(x=>x.date>=from&&x.date<=to&&leagues.some(l=>l.id===x.leagueId)).map(f=>{const cut=f.kickoff??f.date+"T23:59:59Z",h=prior(f.homeTeam,cut),a=prior(f.awayTeam,cut),hg=gfga(h,f.homeTeam),ag=gfga(a,f.awayTeam),lb=leagueBefore(f.leagueId,cut),lh=avg(lb.map(x=>x.homeGoals)),la=avg(lb.map(x=>x.awayGoals)),n=Math.min(h.length,a.length);
 if(n<1||!lh||!la)return {...f,evidenceCutoff:cut,modelLevel:"no-model",sampleSize:n,actualScore:{home:f.homeGoals,away:f.awayGoals},sources:[f.source],noModelReason:"Insufficient reliable pre-kickoff scoring/conceding or league baseline evidence"};
 const homeGF=avg(hg.gf),homeGA=avg(hg.ga),awayGF=avg(ag.gf),awayGA=avg(ag.ga);
 return {date:f.date,kickoff:f.kickoff??cut,leagueId:f.leagueId,homeTeam:f.homeTeam,awayTeam:f.awayTeam,evidenceCutoff:cut,modelLevel:"basic",sampleSize:n,inputs:{homeAttack:homeGF/lh,homeDefence:homeGA/la,awayAttack:awayGF/la,awayDefence:awayGA/lh,leagueHomeGoals:lh,leagueAwayGoals:la,recentHomeAttack:homeGF/lh,recentHomeDefence:homeGA/la,recentAwayAttack:awayGF/la,recentAwayDefence:awayGA/lh,homeScoringRate:h.filter(x=>(x.homeTeam===f.homeTeam?x.homeGoals:x.awayGoals)>0).length/h.length,awayScoringRate:a.filter(x=>(x.homeTeam===f.awayTeam?x.homeGoals:x.awayGoals)>0).length/a.length,recentOver35Rate:[...h,...a].filter(x=>x.homeGoals+x.awayGoals>3).length/(h.length+a.length),modelLevel:"basic",sampleSize:n},actualScore:{home:f.homeGoals,away:f.awayGoals},sources:[f.source]};
});
const out={fixtures,coverage:data.coverage,provider:{url:adapter,retrievedAt:new Date().toISOString(),method:"chronological-basic-v1"}};
const file=path.join(root,`data/backtest-evidence/${from}_to_${to}.source.json`);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(out,null,2)+"\n");console.log(path.relative(root,file));
