import {gradeBet,parseScore} from "../lib/grading";import fs from "node:fs";import path from "node:path";
const args=process.argv.slice(2),finalize=args.includes("--finalize"),file=args.find(x=>!x.startsWith("--"));
if(!file)throw new Error("Usage: npm run run:validate -- <run-file> [--finalize]");
const r=JSON.parse(fs.readFileSync(file,"utf8")),root=process.cwd(),configured=(JSON.parse(fs.readFileSync(path.join(root,"data/leagues.json"),"utf8")).leagues as any[]).map(x=>x.id);
const terminal=new Set(["BET","NO_BET","NO_MODEL","WIN","LOSS"]),allowedLeague=new Set(["pending","discovering","researching","processing","complete","blocked"]);
const errors:string[]=[],warnings:string[]=[],scan=r.leagueScan??[],fixtures=r.fixtures??[];
if(!Array.isArray(r.leagueScan)||!Array.isArray(r.fixtures))errors.push("Missing leagueScan/fixtures arrays");
const ids=scan.map((x:any)=>x.leagueId),missing=configured.filter(x=>!ids.includes(x)),extra=ids.filter((x:string)=>!configured.includes(x));
if(missing.length)errors.push("Missing configured leagues: "+missing.join(", "));
if(extra.length)errors.push("Unknown leagues: "+extra.join(", "));
if(new Set(ids).size!==ids.length)errors.push("Duplicate league checkpoints");
const fixtureKeys=new Set<string>();
for(const f of fixtures){const key=[f.date??r.date,f.leagueId,f.kickoff??"",f.homeTeam,f.awayTeam].join("|");if(fixtureKeys.has(key))errors.push("Duplicate fixture: "+key);fixtureKeys.add(key);if(!configured.includes(f.leagueId))errors.push("Fixture references unknown league: "+f.leagueId);if(!f.leagueId||!f.homeTeam||!f.awayTeam)errors.push("Fixture missing leagueId/homeTeam/awayTeam");if(terminal.has(f.status)||terminal.has(f.outcome)){if(!Array.isArray(f.sources)||!f.sources.length)errors.push(`${f.leagueId} ${f.homeTeam} v ${f.awayTeam}: terminal fixture missing sources`);if((f.status==="BET"||f.outcome==="WIN"||f.outcome==="LOSS")&&!f.recommendedBet)errors.push(`${f.homeTeam} v ${f.awayTeam}: BET/WIN/LOSS missing recommendedBet`);if((f.status==="NO_MODEL"||f.outcome==="NO_MODEL")&&!f.noModelReason)errors.push(`${f.homeTeam} v ${f.awayTeam}: NO_MODEL missing reason`);if(f.recommendedBet&&(f.outcome==="WIN"||f.outcome==="LOSS")){const s=parseScore(f.actualScore);if(!s)errors.push(`${f.homeTeam} v ${f.awayTeam}: graded bet missing valid actualScore`);else{try{const expected=gradeBet(f.recommendedBet,s);if(f.outcome!==expected)errors.push(`${f.homeTeam} v ${f.awayTeam}: grading mismatch stored=${f.outcome} expected=${expected}`)}catch(e:any){errors.push(`${f.homeTeam} v ${f.awayTeam}: ${e.message}`)}}}}}
for(const l of scan){if(!allowedLeague.has(l.status))errors.push(`${l.leagueId}: invalid league status ${l.status}`);const fx=fixtures.filter((f:any)=>f.leagueId===l.leagueId),unfinished=fx.filter((f:any)=>!terminal.has(f.status)&&!terminal.has(f.outcome));const discovered=Number(l.fixturesDiscovered??fx.length),processed=Number(l.fixturesProcessed??0),recommendationsOnly=r.storagePolicy==="recommended-bets-only";if(!recommendationsOnly&&discovered!==fx.length)errors.push(`${l.leagueId}: fixturesDiscovered does not match saved fixtures`);if(!recommendationsOnly&&processed!==fx.length-unfinished.length)errors.push(`${l.leagueId}: fixturesProcessed does not match terminal fixtures`);if(recommendationsOnly&&processed>discovered)errors.push(`${l.leagueId}: fixturesProcessed exceeds fixturesDiscovered`);if(recommendationsOnly&&fx.length>processed)errors.push(`${l.leagueId}: saved recommendations exceed processed fixtures`);if(recommendationsOnly&&l.status==="complete"&&processed!==discovered)errors.push(`${l.leagueId}: complete but processed ${processed}/${discovered}`);if(l.status==="complete"&&unfinished.length)errors.push(`${l.leagueId}: complete with ${unfinished.length} unfinished saved recommendation(s)`);if(l.status==="complete"&&discovered===0&&(!Array.isArray(l.sources)||l.sources.length===0))errors.push(`${l.leagueId}: zero-fixture completion has no verification source`);if(l.status==="blocked"&&!l.blocker)errors.push(`${l.leagueId}: blocked without blocker reason`);}
const unfinished=fixtures.filter((f:any)=>!terminal.has(f.status)&&!terminal.has(f.outcome)),incomplete=scan.filter((l:any)=>l.status!=="complete");
let ready=errors.length===0&&scan.length===configured.length&&unfinished.length===0&&incomplete.length===0;
if(r.status==="complete"&&!ready)errors.push("Run status complete but finalization invariants fail");
if(r.status==="blocked"&&!r.blocker)errors.push("Run blocked without blocker reason");
if(finalize&&!ready)errors.push("Finalization requested before all configured leagues and fixtures are complete");
ready=errors.length===0&&scan.length===configured.length&&unfinished.length===0&&incomplete.length===0;
if(!finalize&&!ready)warnings.push("Run is internally checkable but not ready to finalize");
const computed={mode:finalize?"finalize":"integrity",configuredLeagues:configured.length,leaguesPresent:scan.length,leaguesComplete:scan.length-incomplete.length,fixturesDiscovered:fixtures.length,fixturesTerminal:fixtures.length-unfinished.length,fixturesPending:unfinished.length,readyToFinalize:ready};
console.log(JSON.stringify({file,computed,errors,warnings},null,2));if(errors.length)process.exit(2);
