import fs from "node:fs";
const c=JSON.parse(fs.readFileSync("automation/FIH_CONTRACT.json","utf8"));
const required=["1X2","Total Goals","Double Chance"];
if(c.production.modelVersion!=="v2.9-market-specific-quality-selector") throw new Error("Production model version mismatch");
if(c.contractVersion!=="2.9.0") throw new Error("Canonical contract version mismatch");
if(JSON.stringify(c.markets.requiredFamilies)!==JSON.stringify(required)) throw new Error("Canonical market scope mismatch");
if(JSON.stringify(c.markets.actionable?.["1X2"])!==JSON.stringify(["Home","Draw","Away"])) throw new Error("1X2 picks mismatch");
if(JSON.stringify(c.markets.actionable?.["Total Goals"])!==JSON.stringify(["Over 1.5"])) throw new Error("Total Goals picks mismatch");
if(JSON.stringify(c.markets.actionable?.["Double Chance"])!==JSON.stringify(["1X","X2"])) throw new Error("Double Chance picks mismatch");
if(c.markets.supportingSignals?.["Over 1.5"]?.rawMinimum!==68) throw new Error("Over 1.5 support floor mismatch");
if(c.markets.supportingSignals?.["1X"]?.rawMinimum!==62) throw new Error("1X support floor mismatch");
if(c.markets.supportingSignals?.["X2"]?.rawMinimum!==66) throw new Error("X2 support floor mismatch");
if(c.recommendation?.rawMinimums?.["X2"]!==76) throw new Error("X2 raw floor mismatch");
if(c.recommendation?.selectionProbabilityMinimums?.["X2"]!==72) throw new Error("X2 selection probability floor mismatch");
if(c.recommendation?.marketTemperature?.["1X"]!==1.025||c.recommendation?.marketTemperature?.["X2"]!==1.55||c.recommendation?.marketTemperature?.["Over 1.5"]!==1.025) throw new Error("Market temperature calibration mismatch");
const pub=c.recommendation?.publishProbabilityMinByPick??{};
if(pub["1X"]!==82||pub["Over 1.5"]!==78||pub["X2"]!==78||pub.Home!==78||pub.Draw!==78||pub.Away!==78) throw new Error("V2.9 publication probability floors mismatch");
const margin=c.recommendation?.minimumSupportMarginByPick??{};
if(margin["1X"]!==5||margin["Over 1.5"]!==7||margin["X2"]!==5) throw new Error("V2.9 support margin floors mismatch");
if(c.recommendation?.calibration?.method!=="shrink-toward-50") throw new Error("Calibration method mismatch");
if(c.recommendation?.calibration?.marketDivergenceWatch!==20||c.recommendation?.calibration?.marketDivergenceReview!==30) throw new Error("Market divergence gates mismatch");
if(c.recommendation?.lambdaRisk?.high!==3||c.recommendation?.lambdaRisk?.low!==0.25||c.recommendation?.lambdaRisk?.totalHigh!==4.8) throw new Error("Lambda risk gates mismatch");
for(const key of ["extremeLambdaMustNotAutoPublish","extremeMarketDivergenceMustNotAutoPublish","reviewBetIsNotPublicRecommendation","supportGateRequiredForSaferMarkets","marketSpecificPublicationGateRequired","publicProbabilityMustUseMarketSpecificCalibration"]) if(c.invariants?.[key]!==true) throw new Error("Missing invariant: "+key);
if(c.mutationPolicy.runtimeRuleCreation!=="forbidden") throw new Error("Runtime rule creation must remain forbidden");
if(c.selfCorrection.mayChangeBusinessRules!==false) throw new Error("Self-correction may not change business rules");
if(c.markets.maximumRecommendedBetsPerFixture!==1) throw new Error("One-bet invariant changed");
console.log(JSON.stringify({status:"contract-verified",contractVersion:c.contractVersion,modelVersion:c.production.modelVersion,markets:c.markets.requiredFamilies}));
